### ISSUE TITLE
I'm fucked..

### ISSUE THREAD

**Issue by MYKO133** [AzAgarampur/byeintegrity8-uac#3]
Ayo g  what's cracking. Me and a friend are using BI8 for a "school project" and while i had it in my computer it somehow created a "panther" folder inside the folder i had it and now my WD is erased, i cant open task manager or regedit and bassically im fucked.. how do i remove it and stop it?

**Comment by AzAgarampur** [comment]
bruh

Boot into the recovery environment and mount your user's registry hive and then navigate to `HKEY_USERS\your_user_sid\Environment` and then delete the `windir` variable.

The panther folder was created because windows background setup/servicing components use the windir variable for their log files, so since you created a new windir, the log files will be written to a new panther folder rather than the one in `C:\Windows\Panther`

**Comment by MYKO133** [comment]
Thanks for replying(even after a week or smth) I just formated my pc it's
all good now.. From now on the "school project" will only be tested in
vbox..

**Comment by AzAgarampur** [comment]
gotchu
